### PR TITLE
Fix 169/171

### PR DESCRIPTION
**Pull request by tBuLi**
Solves the issue by instructing `sympy`'s printer on how this object should be printed.

### CODE REVIEW

**Comment by tBuLi** [comment]
Just making objects tell sympy how they would like to be printed does not seem to be enough yet with sympy 1.2, follow the discussion on sympy's issue tracker linked in #171 for more details.

**Comment by pckroon** [comment]
This PR also makes Travis install sympy 1.1, making it misleading. Also change the requirements in this PR.

**Comment by tBuLi** [comment]
Cleaned up the commit history somewhat.

**Comment by tBuLi** [comment]
Actually I just found out that there is also still the same problem in sympy, which I had fixed but forgotten about :P. So it turns out that this change is indeed needed on our end, but I also have to make a PR for sympy.

**Comment by tBuLi** [comment]
Solved with #199

**Pull request closed without merging**
