### PR TITLE
Add analytical Hessian to Model. Clean up Jacobian reshaping

### PR DESCRIPTION
**Pull request by pckroon**
The Hessian still needs to be added to the rest of the machinery: Objectives and Minimizers; but I want a hand with that. Especially for Objectives the maths is annoying

### CODE REVIEW

**Comment by tBuLi** [comment]
Which objectives do you think require this? I think `LeastSquares` and `MinimizeModel` should do?

**Comment by pckroon** [comment]
And maybe `LogLikelihood` as well. It depends on how much time you have available and how hard it is ;)

**Comment by tBuLi** [comment]
Getting on it now

**Comment by tBuLi** [comment]
Superseded and solved in #199.

**Pull request closed without merging**
